"""empty message

Revision ID: 0673392058fd
Revises: a9b273500a6e
Create Date: 2021-01-17 09:42:23.123075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0673392058fd'
down_revision = 'a9b273500a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'num_comment',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'num_comment',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
