"""empty message

Revision ID: 82c01d2cd534
Revises: 2c7148e2ad2e
Create Date: 2021-02-04 18:52:51.622741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c01d2cd534'
down_revision = '2c7148e2ad2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_active')
    # ### end Alembic commands ###
