"""empty message

Revision ID: 8ee8d79b9317
Revises: d65593066fb5
Create Date: 2021-01-21 20:16:18.251763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ee8d79b9317'
down_revision = 'd65593066fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('urlImg', sa.Text(), nullable=True))
    op.drop_column('user', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', mysql.TEXT(), nullable=True))
    op.drop_column('user', 'urlImg')
    # ### end Alembic commands ###
