"""empty message

Revision ID: c67799066c6b
Revises: c3fdf151114a
Create Date: 2021-02-01 15:41:40.460692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c67799066c6b'
down_revision = 'c3fdf151114a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'recipe_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'recipe_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
