"""empty message

Revision ID: d65593066fb5
Revises: f94e3e14cf5f
Create Date: 2021-01-20 10:12:20.966580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65593066fb5'
down_revision = 'f94e3e14cf5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('user_name', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'image')
    # ### end Alembic commands ###
