"""empty message

Revision ID: f23251330974
Revises: 
Create Date: 2021-01-30 11:30:09.091739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f23251330974'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_category', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_category')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('ingredients', sa.String(length=250), nullable=False),
    sa.Column('elaboration', sa.String(length=250), nullable=False),
    sa.Column('num_comment', sa.Integer(), nullable=True),
    sa.Column('date_recipe', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe__category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('id_recipe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['id_recipe'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('comments', 'date_comment',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('comments', 'recipe_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'recipe_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'date_comment',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_table('recipe__category')
    op.drop_table('recipe')
    op.drop_table('category')
    # ### end Alembic commands ###
